### PR TITLE
[Enhancement] add information_schema.table_options(#32572)

### PR DESCRIPTION
**Pull request by Vallishp**
add document for information_schema.table_options table.
code PR https://github.com/apache/doris/pull/34384

### CODE REVIEW

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Comment by luzhijing** [comment]
Please add the CN docs and update the sidebar.json

**Comment by xinyiZzz** [comment]
```
diff --git a/sidebars.json b/sidebars.json
index de5351eba98..e99462be973 100644
--- a/sidebars.json
+++ b/sidebars.json
@@ -476,7 +476,8 @@
                 "admin-manual/plugin-development-manual",
                 "admin-manual/small-file-mgr",
                 "admin-manual/compaction",
-                "admin-manual/rowsets"
+                "admin-manual/rowsets",
+                "admin-manual/table_options"
             ]
         },
         {
```

**Review by morningman — COMMENTED** [review]
Do not merge

**Comment by Vallishp** [comment]
closing this, raise another PR

**Pull request closed without merging**
