### PR TITLE
[docs](trash) update trash default expire time

### PR DESCRIPTION
**Pull request by zhannngchen**
update trash default expire time to 1 day

see https://github.com/apache/doris/pull/37170

### CODE REVIEW

**Comment by zhannngchen** [comment]
run buildall

**Comment by luzhijing** [comment]
Waiting for #37170 merged.

**Comment by luzhijing** [comment]
Is the 2.1-branch docs also need to update?

**Comment by zhannngchen** [comment]
> Is the 2.1-branch docs also need to update?

yes, I'll update that

**Review by luzhijing — APPROVED** [review]
LGTM

**Pull request merged**
