### PR TITLE
[doc] fix release-2.1.0.md

### PR DESCRIPTION
**Pull request by DarvenDuan**
create table stmt is not correct

### CODE REVIEW

**Review by luzhijing — APPROVED** [review]
LGTM

**Comment by luzhijing** [comment]
Please also fix the 2.1-branch (https://github.com/apache/doris-website/blob/master/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/releasenotes/release-2.1.0.md)

**Comment by DarvenDuan** [comment]
> Please also fix the 2.1-branch (https://github.com/apache/doris-website/blob/master/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/releasenotes/release-2.1.0.md)

have done

**Review by luzhijing — APPROVED** [review]
LGTM

**Review by shasevendow — APPROVED** [review]

**Pull request merged**
