### PR TITLE
Update load-manual.md

### PR DESCRIPTION
**Pull request by Ruffianjiang**
修复【实时写入】中的 Stream Load 的链接地址

# Versions 

- [x] dev
- [x] 3.0
- [x] 2.1
- [ ] 2.0

# Languages

- [x] Chinese
- [x] English

### CODE REVIEW

**Comment by liaoxin01** [comment]
@Ruffianjiang please add this fix to branch dev and 2.1.

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Comment by Ruffianjiang** [comment]
> @Ruffianjiang please add this fix to branch dev and 2.1.

The changes have already been merged into the dev and 2.1 branches.

Thx.

**Comment by liaoxin01** [comment]
There are also issues with the English document, please fix it.

**Comment by Ruffianjiang** [comment]
> There are also issues with the English document, please fix it.

English document has also been updated.

**Review by liaoxin01 — APPROVED** [review]
LGTM

**Pull request merged**
