### PR TITLE
[doc]drop-table page fix RECOVER link fair for 2.1 version

### PR DESCRIPTION
**Pull request by cjj2010**
close issue #719

### CODE REVIEW

**Review by shasevendow — APPROVED** [review]
LGTM

**Comment by shasevendow** [comment]
Does version 2.1 need to be updated too?

**Comment by cjj2010** [comment]
> Does version 2.1 need to be updated too?

It's necessary, it's already taken care of now

**Review by KassieZ — APPROVED** [review]

**Comment by cjj2010** [comment]
Already fixed https://github.com/apache/doris-website/pull/1091

**Pull request closed without merging**
