### PR TITLE
add strcmp doc

### PR DESCRIPTION
**Pull request by xiedeyantu**

### CODE REVIEW

**Comment by xiedeyantu** [comment]
doc for https://github.com/apache/doris/pull/33272

**Review by zclllyybb — APPROVED** [review]
LGTM. cc @luzhijing please merge it

**Comment by luzhijing** [comment]
Please add it in sidebar.json

**Comment by xiedeyantu** [comment]
> Please add it in sidebar.json

@luzhijing done, please review.

**Review by luzhijing — APPROVED** [review]
LGTM

**Pull request merged**
