### PR TITLE
[typo]Fix typo in arrow flight documentation

### PR DESCRIPTION
**Pull request by DongLiang-0**

### CODE REVIEW

**Review by luzhijing — COMMENTED** [review]
Please also fix it in branch-3.0

**Review by luzhijing — COMMENTED** [review]
Please also fix it in branch-3.0

**Comment by DongLiang-0** [comment]
> Please also fix it in branch-3.0

done!

**Review by luzhijing — APPROVED** [review]
LGTM

**Review by KassieZ — APPROVED** [review]

**Pull request merged**
