### PR TITLE
[typo](doc) fix some typo in data_model section

### PR DESCRIPTION
**Pull request by AcKing-Sam**

### CODE REVIEW

**Review by luzhijing — COMMENTED** [review]
This doc will keep consistent with 2.0-branch.

**Comment by AcKing-Sam** [comment]
> This doc please keep consistent with 2.0-branch.

@luzhijing  Hi, do you mean adding v2.0's files?

In addition, need I remove v2.1's files?

**Comment by luzhijing** [comment]
> > This doc please keep consistent with 2.0-branch.
> 
> @luzhijing Hi, do you mean adding v2.0's files?
> 
> In addition, need I remove v2.1's files?

You can refer to the 2.0-branch docs : https://doris.apache.org/docs/2.0/table-design/data-model/overview

**Comment by AcKing-Sam** [comment]
@luzhijing  Done! Thanks for your guide!
In addition, I found in v2.0, the [usage guideline section](https://doris.apache.org/docs/2.0/table-design/data-model/tips/) is in the `data-model` part. Which is different from v2.1 and master(usage guideline are parallel to data model).

**Pull request closed without merging**
