### PR TITLE
[doc]delete sql manual docs that mismatched of code in 2.0

### PR DESCRIPTION
**Pull request by mongo360**
delete same mismatched sql manual doc for 2.0 in Database-Administration-Statements

This 3 admin command does not implement in 2.0 version:
1. ADMIN-SET-PARTITION-VERSION
related pr: https://github.com/apache/doris/pull/23086
3. ADMIN-SET-REPLICA-VERSION
related pr: https://github.com/apache/doris/pull/23706
5. ADMIN-SET-TABLE-STATUS
 related pr: https://github.com/apache/doris/pull/23139

replicate:
test table
```
MySQL [db]> create table a_table(
    k1 BIGINT NOT NULL,
    k2 DATE NOT NULL,
    k3 VARCHAR(100) NOT NULL,
    v1 INT SUM NULL DEFAULT "0"
) ENGINE=OLAP
AGGREGATE KEY(k1,k2,k3)
PARTITION BY RANGE(`k2`)
(PARTITION pbefore202305 VALUES [('1900-01-01'), ('2023-05-01')),
PARTITION p202305 VALUES [('2023-05-01'), ('2023-06-01')),
PARTITION p202306 VALUES [('2023-06-01'), ('2023-07-01')))
distributed BY hash(k1) buckets 2
properties("replication_num" = "1");
MySQL [db]> insert into a_table values (10, '2023-06-05', 'view', 100);
```
1. ADMIN-SET-PARTITION-VERSION test
```
MySQL [db]> admin set table a_table partition version properties ('partition_id'="10086", "visible_version" = "2");
ERROR 1105 (HY000): errCode = 2, detailMessage = Syntax error in line 1:
admin set table a_table partition vers...
          ^
Encountered: TABLE
Expected
```
2. ADMIN-SET-REPLICA-VERSION test
```
MySQL [db]> ADMIN SET REPLICA VERSION PROPERTIES("tablet_id" = "10097", "backend_id" = "10012", "last_failed_version" = "-1");
ERROR 1105 (HY000): errCode = 2, detailMessage = Syntax error in line 1:
ADMIN SET REPLICA VERSION PROPERTIES("tablet_i...
                  ^
Encountered: VERSION
Expected
```
3. ADMIN-SET-TABLE-STATUS test
```
MySQL [db]> admin set table a_table status properties("state" = "NORMAL");
ERROR 1105 (HY000): errCode = 2, detailMessage = Syntax error in line 1:
admin set table a_table status propert...
          ^
Encountered: TABLE
Expected
```

### CODE REVIEW

**Review by zclllyybb — COMMENTED** [review]
please also delete them in sidebars.json

**Comment by mongo360** [comment]
> please also delete them in sidebars.json

done

**Comment by luzhijing** [comment]
Thank you for your contribution. Could you please elaborate on the specific manifestations of the mismatch between these documents and the code? Please provide a detailed explanation.

**Comment by mongo360** [comment]
> Thank you for your contribution. Could you please elaborate on the specific manifestations of the mismatch between these documents and the code? Please provide a detailed explanation.

@luzhijing added

**Review by luzhijing — APPROVED** [review]
LGTM

**Review by zclllyybb — APPROVED** [review]
LGTM

**Pull request merged**
