### PR TITLE
[doc][fe] Fix fe metadata operation doc error

### PR DESCRIPTION
**Pull request by SWJTU-ZhangLei**
* fix `metadata-operation.md` doc error
* remove fe metadata recovery mode step

### CODE REVIEW

**Review by luzhijing — COMMENTED** [review]
Please also fix the 2.0/2.1-branch docs

**Comment by luzhijing** [comment]
There are some conflicts and please rebase the code.

**Review by w41ter — APPROVED** [review]

**Review by dataroaring — APPROVED** [review]
LGTM

**Review by luzhijing — APPROVED** [review]
LGTM

**Pull request merged**
