### PR TITLE
[typo](docs) fix spelling error of double in release-2.0.3.md

### PR DESCRIPTION
**Pull request by wanghuan2054**

### CODE REVIEW

**Review by luzhijing — COMMENTED** [review]
Thanks for your contributions, would you please fix it in branch-2.0 and branch-2.1?

**Comment by wanghuan2054** [comment]
> Thanks for your contributions, would you please fix it in branch-2.0 and branch-2.1?

ok

**Comment by luzhijing** [comment]
En: https://github.com/apache/doris-website/tree/master/versioned_docs/version-2.1
En: https://github.com/apache/doris-website/tree/master/versioned_docs/version-2.0
Cn: https://github.com/apache/doris-website/tree/master/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1
Cn: https://github.com/apache/doris-website/tree/master/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0

**Comment by wanghuan2054** [comment]
> Thanks for your contributions, would you please fix it in branch-2.0 and branch-2.1?

ok

**Pull request merged**
