### PR TITLE
[doc](alter) alter to add partitions in batches

### PR DESCRIPTION
**Pull request by felixwluo**
`For the alter operation, add partitions in batches`
doris pr: https://github.com/apache/doris/pull/37114

### CODE REVIEW

**Comment by shasevendow** [comment]
Please attach the code PR link.

**Comment by felixwluo** [comment]
> Please attach the code PR link.

done

**Review by shasevendow — APPROVED** [review]
LGTM

**Comment by shasevendow** [comment]
Does the 2.1 version need to be updated too?

**Comment by felixwluo** [comment]
> Does the 2.1 version need to be updated too?

Yes, this feature is implemented in 2.1

**Comment by shasevendow** [comment]
> > Does the 2.1 version need to be updated too?
> 
> Yes, this feature is implemented in 2.1

Please refer to the contribution guide to update the 2.1 version docs: https://doris.apache.org/zh-CN/community/how-to-contribute/contribute-doc/

**Review by KassieZ — COMMENTED** [review]
please also update version 3.0 / 2.1 / 2.0

**Comment by felixwluo** [comment]
> please also update version 3.0 / 2.1 / 2.0

done

**Review by KassieZ — APPROVED** [review]

**Comment by KassieZ** [comment]
Hi, thank you for your contribution.  The build cannot be triggered, so it is recommended to pull request again.

**Comment by felixwluo** [comment]
Do I need to close this pull request and submit a new one?

KassieZ ***@***.***>于2024年9月2日 周一10:44写道：

**Comment by felixwluo** [comment]
> Hi, thank you for your contribution. The build cannot be triggered, so it is recommended to pull request again.

https://github.com/apache/doris-website/pull/1077

**Pull request closed without merging**
