### PR TITLE
[doc] fix mysql ssl pack server-key common

### LINKED ISSUE #844: Setting mysql SSL pack command error
when execute
```
openssl pkcs12 -inkey server-key.pem -in server.pem -export -out server_certificate.p12
```
error
2024-07-09 15-33-03屏幕截图

### PR DESCRIPTION
**Pull request by cjj2010**
close #844

### CODE REVIEW

**Comment by shasevendow** [comment]
Please also update the English documents in version 2.1 & 2.0.

**Comment by cjj2010** [comment]
> Please also update the Chinese documents in dev version and English documents in 2.1 & 2.0 versions.

I can't find English documents in 2.1 & 2.0 versions on master and other version is already modify

**Comment by shasevendow** [comment]
> > Please also update the Chinese documents in dev version and English documents in 2.1 & 2.0 versions.
> 
> I can't find English documents in 2.1 & 2.0 versions on master and other version is already modify

You can refer to the contribution guide to find the corresponding docs: https://doris.apache.org/zh-CN/community/how-to-contribute/contribute-doc/#02-%E6%96%87%E6%A1%A3%E7%9B%AE%E5%BD%95

**Comment by cjj2010** [comment]
> > > Please also update the Chinese documents in dev version and English documents in 2.1 & 2.0 versions.
> > 
> > 
> > I can't find English documents in 2.1 & 2.0 versions on master and other version is already modify
> 
> You can refer to the contribution guide to find the corresponding docs: https://doris.apache.org/zh-CN/community/how-to-contribute/contribute-doc/#02-%E6%96%87%E6%A1%A3%E7%9B%AE%E5%BD%95

thanks, now is already fix it.

**Review by shasevendow — APPROVED** [review]
LGTM

**Review by luzhijing — APPROVED** [review]
LGTM

**Pull request merged**
