### PR TITLE
[doc](fqdn) fix fqdn doc

### PR DESCRIPTION
**Pull request by codegit10001**
[doc] fix some wrong description of fqdn doc，and add some detailed explanations。

### CODE REVIEW

**Review by luzhijing — COMMENTED** [review]
Please also fix it in cn master-branch and 2.1/2.0 branch.

CN master branch : https://github.com/apache/doris-website/tree/master/i18n/zh-CN/docusaurus-plugin-content-docs/current
EN 2.0-branch: https://github.com/apache/doris-website/tree/master/versioned_docs/version-2.0
EN 2.1-branch: https://github.com/apache/doris-website/tree/master/versioned_docs/version-2.1

**Review by morningman — APPROVED** [review]
LGTM

**Comment by codegit10001** [comment]
> Please also fix it in cn master-branch and 2.1/2.0 branch.
> 
> CN master branch : https://github.com/apache/doris-website/tree/master/i18n/zh-CN/docusaurus-plugin-content-docs/current EN 2.0-branch: https://github.com/apache/doris-website/tree/master/versioned_docs/version-2.0 EN 2.1-branch: https://github.com/apache/doris-website/tree/master/versioned_docs/version-2.1

done！

**Review by luzhijing — APPROVED** [review]
LGTM

**Pull request merged**
