### PR TITLE
Add insert overwriter partiton(*) version support

### PR DESCRIPTION
**Pull request by caoliang-web**
Add insert overwriter partiton(*) version support

### CODE REVIEW

**Review by shasevendow — APPROVED** [review]
LGTM

**Comment by luzhijing** [comment]
Please also change the dev-branch.

**Comment by zclllyybb** [comment]
> Please also change the dev-branch.

why should change it? I think dev-branch always represents the behaviour of the master branch code so it doesn't have to have any version label.

**Review by zclllyybb — APPROVED** [review]
LGTM

**Review by luzhijing — APPROVED** [review]
LGTM

**Pull request merged**
