### PR TITLE
[Feature] Support CREATE DB COMMENT (#16678)

### PR DESCRIPTION
**Pull request by xiabaike**
When create a database, add support for comment, which explains something about the database so that people who see it know what it is and what it does. CREATE DATABASE [IF NOT EXISTS] db_name COMMENT database_comment [PROPERTIES ("key"="value", ...)]; Add database's comment to the result of the SHOW CREATE DATABASE statement.

### CODE REVIEW

**Comment by xiabaike** [comment]
doris's pull:
https://github.com/apache/doris/pull/34455

**Comment by luzhijing** [comment]
New pull request: 
https://github.com/apache/doris/pull/34625

**Comment by xiabaike** [comment]
> New pull request: [apache/doris#34625](https://github.com/apache/doris/pull/34625)

thanks

**Comment by luzhijing** [comment]
Waiting the https://github.com/apache/doris/pull/34625 merged.

**Review by KassieZ — COMMENTED** [review]
if version 3.0/2.1/2.0 also support this feature, please update the according docs as well, thank you.

**Pull request closed without merging**
